give @s pa:beetroot_cake
give @s pa:big_yeti_fur
give @s pa:bigobsidian_shard
give @s pa:bigobsidian_sword
give @s pa:bessingfromthehel
give @s pa:change_mithing
give @s pa:compressedfire
give @s pa:cooked_yeti_meat
give @s pa:core
give @s pa:candy
give @s pa:crab_boot
give @s pa:candy_scythe
give @s pa:crab_helmet
give @s pa:crab_core
give @s pa:crab_legging
give @s pa:crab_upper_body
give @s pa:crab_hand
give @s pa:crab_lower_body
give @s pa:crab_leg
give @s pa:crab_sword
give @s pa:dark_night_helmet
give @s pa:dark_night_ingot
give @s pa:crabl_chestplate
give @s pa:dark_night_chestplate
give @s pa:dark_night_apple
give @s pa:dark_night_boot
give @s pa:dark_night_legging
give @s pa:dark_soul_apple
give @s pa:dark_soul_ingot
give @s pa:dau_ghitar
give @s pa:diaicesteelboot
give @s pa:diaicesteelchestplates
give @s pa:diaicesteelhelmets
give @s pa:diaicesteellegging
give @s pa:emerald_apple
give @s pa:emerald_sword
give @s pa:emerald_helmet
give @s pa:emerald_boot
give @s pa:emerald_legging
give @s pa:emerald_chestplate
give @s pa:diamonspear
give @s pa:ender_dust
give @s pa:firejade
give @s pa:firefeather
give @s pa:fire_dust
give @s pa:enderjade
give @s pa:frozen_boot
give @s pa:frozemeral_chestplate
give @s pa:frozen_heart
give @s pa:frozen_heart_piece
give @s pa:frozen_chestplate
give @s pa:frozen_hat
give @s pa:frizenscythe
give @s pa:frizen_sword
give @s pa:frozen_helmet
give @s pa:frozen_legging
give @s pa:frozenheart
give @s pa:frozensteel
give @s pa:frozen_sword
give @s pa:frozendsword
give @s pa:frozenscythe
give @s pa:frozendscythe
give @s pa:frozether_legging
give @s pa:frozpeed_boot
give @s pa:guitar
give @s pa:handgiantzombie
give @s pa:fur_block
give @s pa:hayhead
give @s pa:iceore
give @s pa:icesteel
give @s pa:ice_bar
give @s pa:harvester_scythe
give @s pa:nightvisionhelmet
give @s pa:longobsidian_sword_upgrage
give @s pa:obsidian_battle_axe
give @s pa:longobsidian_sword
give @s pa:obsidian_battle_axebig
give @s pa:obsidian_sharp
give @s pa:obsidian_sword
give @s pa:obsidiancarrot
give @s pa:obsidian_chestplate
give @s pa:obsidian_boot
give @s pa:obsidian_helmet
give @s pa:obsidian_leggings
give @s pa:reaper_skull
give @s pa:rawfrozensteel
give @s pa:red_ore
give @s pa:raw_rast_iron
give @s pa:raw_steel
give @s pa:rawicesteel
give @s pa:red_ore_piece
give @s pa:protection_of_the_sea
give @s pa:scarecrow
give @s pa:steel_ingot
give @s pa:soul
give @s pa:steel_stick
give @s pa:red_steel
give @s pa:steel_sword
give @s pa:ugage_emeral_helmet
give @s pa:thrownhdbrbr
give @s pa:thitthoiran
give @s pa:super_smithing_update
give @s pa:than_ghitar
give @s pa:tast_iron_ingot
give @s pa:the_trust_of_the_village
give @s pa:the_blessing_of_food
give @s pa:utra_change_smithing
give @s pa:waterofzombie
give @s pa:utimate_emeral_helmet
give @s pa:utrasmithing
give @s pa:update_diamon_spear
give @s pa:yeti_fur
give @s pa:yeti_meat
give @s pa:yeti_core
give @s pa:zombieaxe
give @s pa:zombie_heart
