give @s pa:dark_night_apple
give @s pa:dark_night_boot
give @s pa:dark_night_chestplate
give @s pa:dark_night_helmet
give @s pa:dark_night_ingot
give @s pa:dark_night_legging
give @s pa:dark_soul_apple
give @s pa:dark_soul_ingot
give @s pa:harvester_scythe
give @s pa:raw_rast_iron
give @s pa:raw_steel
give @s pa:reaper_skull
give @s pa:soul
give @s pa:steel_ingot
give @s pa:steel_stick
give @s pa:steel_sword
give @s pa:super_smithing_update
give @s pa:tast_iron_ingot
