import "./item_trigger";
import "./durability_manager";
import "./giantzombie";
import "./yeti_phase_1";
import "./yeti_phase_2";
import "./yeti_phase_3";
import "./robot_crap";
import "./scythe_frozen";
import "./chestplate_frozen";
import "./scythe_frizen";
import "./scythe_frozend";
import "./armor";
import "./harvester";
import "./frozen_heart";
import "./harvester_scythe";
import "./utimate_emeral_helmet";
console.warn("All boss skills loaded!");